# Generated by Django 2.2.3 on 2019-07-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dateAndTime',
            field=models.DateTimeField(verbose_name='date uploaded'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='topicSection',
        ),
        migrations.AddField(
            model_name='message',
            name='topicSection',
            field=models.ManyToManyField(to='ebc_app.TopicSection'),
        ),
    ]
